name: Ã–dev
on:
  push:
  workflow_dispatch:

jobs:
  assignment:
    runs-on: ubuntu-latest
    env:     { DISTRO_PATH: '.local/opt' }
    steps:
      - name: Getir ğŸ›ï¸
        uses: actions/checkout@v2.4.0

      - name: HazÄ±rla ğŸ¥
        uses: actions/checkout@v2
        with: { repository: 'alaturka/linux', path: '${{ env.DISTRO_PATH }}' }

      - name: HazÄ±rla ğŸ¥
        run:  printf '%s\n%s\n' "$DISTRO_PATH"/bin "$DISTRO_PATH"/opt/self/usr/bin >>"$GITHUB_PATH"

      - name: NotlandÄ±r ğŸ“
        uses: education/autograding@v1
